apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-staging
  namespace: argocd
  annotations:
    # Authorise the Kargo `staging` Stage to sync this Application.
    kargo.akuity.io/authorized-stage: argocd-getting-started:staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argocd-getting-started
  source:
    repoURL: https://github.com/gsaini/argocd-getting-started.git
    targetRevision: main
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-demo-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
